import type { Person, PersonTotalTime } from "src/generated/client";

export const mockPersons: Person[] = [
  {
    id: 0,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    monday: 0,
    tuesday: 0,
    wednesday: 0,
    thursday: 0,
    friday: 0,
    saturday: 0,
    sunday: 0,
    active: true,
    language: "English",
    startDate: "2023-01-01",
    unspentVacations: 0,
    spentVacations: 0,
    minimumBillableRate: 0,
    keycloakId: "0"
  },
  {
    id: 1,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    monday: 0,
    tuesday: 0,
    wednesday: 0,
    thursday: 0,
    friday: 0,
    saturday: 0,
    sunday: 0,
    active: true,
    language: "English",
    startDate: "2023-02-01",
    unspentVacations: 2,
    spentVacations: 1,
    minimumBillableRate: 50,
    keycloakId: "1"
  },
  {
    id: 2,
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    monday: 0,
    tuesday: 0,
    wednesday: 0,
    thursday: 0,
    friday: 0,
    saturday: 0,
    sunday: 0,
    active: false,
    language: "Spanish",
    startDate: "2023-03-01",
    unspentVacations: 5,
    spentVacations: 3,
    minimumBillableRate: 60,
    keycloakId: "2"
  },
  {
    id: 3,
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    monday: 0,
    tuesday: 0,
    wednesday: 0,
    thursday: 0,
    friday: 0,
    saturday: 0,
    sunday: 0,
    active: true,
    language: "French",
    startDate: "2023-04-01",
    unspentVacations: 10,
    spentVacations: 2,
    minimumBillableRate: 70,
    keycloakId: "3"
  },
  {
    id: 4,
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@example.com",
    monday: 0,
    tuesday: 0,
    wednesday: 0,
    thursday: 0,
    friday: 0,
    saturday: 0,
    sunday: 0,
    active: true,
    language: "German",
    startDate: "2023-05-01",
    unspentVacations: 0,
    spentVacations: 0,
    minimumBillableRate: 80,
    keycloakId: "4"
  }
];

export const mockPersonTotalTime: PersonTotalTime[] = [{
  balance: 0,
  billableProjectTime: 0,
  nonBillableProjectTime: 0,
  expected: 0,
  internalTime: 0,
  logged: 0,
  loggedProjectTime: 0,
  personId: 3,
  timePeriod: "2021-07-31,2024-06-19"
}]

